- hosts: 192.168.0.1
  roles:
     - { role: keepalived, keepalived_shared_ip: "192.168.0.5", keepalived_priority: 100, keepalived_role: "MASTER" }

- hosts: 192.168.0.2
  roles:
     - { role: keepalived, keepalived_shared_ip: "192.168.0.5", keepalived_priority: 99, keepalived_role: "MASTER" }
