- hosts: 192.168.0.1
  roles:
     - { role: keepalived, keepalived_shared_ip: "192.168.0.5", keepalived_role: "master" }

- hosts: 192.168.0.2
  roles:
     - { role: keepalived, keepalived_shared_ip: "192.168.0.5", keepalived_role: "slave" }
