---
# This role installs and sets up keepalived

- name: Install keepalived
  apt: name=keepalived state=latest
  tags: keepalived
  notify: restart keepalived

- name: Configuration de keepalived
  template: src={{item}}.j2 dest=/etc/keepalived/{{item}}
  with_items:
  - "keepalived.conf"
  - "notify.sh"
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
