---
# This role installs and sets up keepalived

- name: Install keepalived
  apt: name=keepalived state=latest
  tags: keepalived
  notify: restart keepalived

- name: Configuration de keepalived
  template: 
      - src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
      - src=notify.sh.j2 dest=/etc/keepalived/notify.sh
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
