---
# This role installs and sets up keepalived

- name: Install keepalived
  apt: name=keepalived state=latest
  tags: keepalived
  notify: restart keepalived

- name: Configuration de keepalived
  template: src={{item.url}}.j2 dest=/etc/keepalived/{{item.url}} mode={{item.b}}
  with_items:
     - { url: 'keepalived.conf', b: '644' }
     - { url: 'notify.sh', b: '544' }
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
